### ISSUE TITLE
Populate Foreclosure

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-velocify#22]
Please populate property_foreclosure in Velocify with the data from `mortgage.bankruptcy.discharged_months_ago`.

Allowed values in Velocify:

Currently in Foreclosure
1-12 months ago
13-24 months ago
25-36 months ago
37-48 months ago
49-60 months ago
61-72 months ago
73-84 months ago
Over 84 months ago
Never Foreclosed

![screen shot 2014-12-30 at 11 10 53 am](https://cloud.githubusercontent.com/assets/8238417/5580744/c4ee211e-9014-11e4-9423-9ba5c73b7264.png)

**Comment by ros3bud** [comment]
@zalary - was this completed?

**Comment by zalary** [comment]
no.  as of now, if the values match our standards, it sends that.  otherwise it doesn't send anything. 

Afaik we haven't heard back on what type of values Velocify will accept yet (just the ranges in the screenshot above or if we can send them any range or any number)

**Comment by kcaponeAP** [comment]
Velocify will not accept any other ranges other than what is in the dropdown. I received an additional bit of information from their support team. The full set of values are as follows:

Property Foreclosure:

Currently in Foreclosure
1-12 months ago
13-24 months ago
25-36 months ago
37-48 months ago
49-60 months ago
61-72 months ago
73-84 months ago
Over 84 months ago
Never Foreclosed

**Comment by kcaponeAP** [comment]
Closing. This has two issues that are lumped together. I will break these apart for clarity and re-open.
