### ISSUE TITLE
Costco.product field for Velocify mapping?

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-velocify#23]
Hello,

I need to make decisions to route leads via costco.product in Velocify. I noticed that the field is not in the drop down. Can someone please assist?

![screen shot 2015-01-27 at 3 40 12 pm](https://cloud.githubusercontent.com/assets/5596/5927785/d8a038aa-a63a-11e4-981c-ee4ae5880e71.png)

What I'm trying to do is map a certain value to velocity.campaign_id if source is equal to costco and product is equal to finance or mobile.

**Comment by cgrayson** [comment]
A standard field for `costco.product` was added in mid-December, I'd guess after Costco was added to the you're looking at, so it wasn't automatically added. You can add it to the flow manually (click the "Add a Field" button, then search for "product", and you should see "Costco Product Type").
