### ISSUE TITLE
address_2 does not pass to velocify integration

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-velocify#29]
https://next.leadconduit.com/events/54d50191bdddc2d54c7a0d59?event_id=54d50195bdddc2d54c7a0d62&source_id=5463d065825ba3336f563c50&type=source&start=2015-02-01&end=2015-02-11

(Please see me in slack for client. Reference is B)

We do not have a space to route address_2 in Velocify. Can we concatenate our address_1 and address_2 to send to Velocify.

**Comment by alexkwolfe** [comment]
We can concatenate them, yes.

**Comment by zalary** [comment]
solved in Version 0.0.12
