### ISSUE TITLE
Add support for customizing Provider

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-velocify#31]

**Comment by alexkwolfe** [comment]
This is high priority. @zalary or @cgrayson, would one of you mind picking this one up?

**Comment by cgrayson** [comment]
Happy to. But what does it mean?

**Comment by alexkwolfe** [comment]
Haha. Sorry. There is a parameter in the querystring called `Provider`. We need to be able to customize that. But actually, hold off for a few minutes. We're discussing further.

**Comment by alexkwolfe** [comment]
I'll re-open later, if necessary.
