### ISSUE TITLE
credit_profile not getting populated with a value

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-velocify#32]
When a value is passed in credit_rating via the Costco integration, it does not end up getting passed to Velocify in credit_profile.

This is specifically for the Leads Con push and needs to get sorted out asap.

See this lead as an example: https://next.leadconduit.com/events/54e631c49bce51171bd38515.

**Comment by zalary** [comment]
this will be resolved once the deprecated fields version of costo is in production.  
this can be fixed manually by mapping the deprecated field (mortgage.application.credit_rating) to the one Velocify is expecting (credit_rating)

**Comment by kcaponeAP** [comment]
Verified to be working in staging

**Comment by kcaponeAP** [comment]
Lead headed outbound for Velocify from the source M.com are not passing the credit value. This is in the simulation flow. 

https://next.staging.leadconduit.com/events/54e762ecc11661067fac8f40?event_id=54e762f1c11661067fac8f4a&type=source&start=2015-02-01&end=2015-02-20

**Comment by alexkwolfe** [comment]
Looks like Military.com is populating a deprecated field.

**Comment by zalary** [comment]
turns out this was happening because the newest version of the integration wasn't in use because I hadn't updated it correctly

@kcaponeAP please check out 
https://next.staging.leadconduit.com/events/54e775301cd3c5456b14a8a8?event_id=54e775311cd3c5456b14a8b2&type=source&start=2015-02-01&end=2015-02-20

I think that it should be resolved now.   please reopen if not

**Comment by kcaponeAP** [comment]
This worked perfect for the lead you posted above. Tyvm. This lead for LT did not pass the credit info:

https://next.staging.leadconduit.com/events/54e7777e1cd3c5456b14a8bc?type=source&start=2015-02-01&end=2015-02-20

**Comment by zalary** [comment]
@kcaponeAP   can you resubmit that one and see if works this time?

**Comment by kcaponeAP** [comment]
Confirmed to be working in lead:

https://next.staging.leadconduit.com/events/54e7a4165e36575d7f6ae2bc?event_id=54e7a4175e36575d7f6ae2c6&type=source&start=2015-02-01&end=2015-02-20

tyvvvvm
