### ISSUE TITLE
Please allow the option to send the ActiveProspect ID in place of Reference ID

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-velocify#38]
One of our clients relies on the usage of the ActiveProspect generated ID to track their leads. 

Is there a way to currently send the AP generated ID to Velocify?

**Comment by zalary** [comment]
in this integration, the reference ID is by default the ActiveProspect generated ID.

That said, it looks like said client (which should not be mentioned in a public repo) is actually delivering from LeadConduit to LCC - and LCC does the delivery to Velocify.  So in that case you'll need to make a field in LCC to capture the reference id and pass it there, then set up the outbound delivery to pass it to Velocify.

**Comment by kcaponeAP** [comment]
They are not delivering from LCC to LCN. This is a direct POST from their system (Boberdoo) into LCN. Costco has never been a live source in LCC. Previous to LCN, they were going Boberdoo --> Mortech.

In this event, can you point me towards that information that we can send. Its not present as part of the 'Data Available at this step' 

https://next.leadconduit.com/events/55004ae31b64a77b0eee6a8a?source_id=54f0cd18c207076637c22415&type=source&start=2015-03-01&end=2015-03-13

**Comment by zalary** [comment]
In that case, you can map Reference Code to {{lead.id}} and that should send our id instead of what they are sending/what we pick up from the reference field

**Comment by kcaponeAP** [comment]
Okie doke. I'll try that. Thanks - wasn't clear by our UI. I'll leave this open until verified to work.

**Comment by cgrayson** [comment]
But no brackets around `lead.id`. 

![screen shot 2015-03-13 at 1 19 20 pm](https://cloud.githubusercontent.com/assets/5596/6644623/98a07f3c-c983-11e4-86eb-953ed900e778.png)

**Comment by kcaponeAP** [comment]
Thanks for that Chris. Was thinking that would be the case. Appreciated all.

**Comment by cgrayson** [comment]
Sorry, we lied. We think it should actually be:

![screen shot 2015-03-13 at 1 27 20 pm](https://cloud.githubusercontent.com/assets/5596/6644770/c599b304-c984-11e4-9f3a-359d2928a3e5.png)

**Comment by kcaponeAP** [comment]
10-4

**Comment by kcaponeAP** [comment]
Hmmm that didn't seem to work. 

Lead ID to lead.reference 

Result is: 
Velocify Reference	= lead.id

https://next.leadconduit.com/events/550331470a56f34b6315ae00?event_id=550331490a56f34b6315ae07

Thoughts?

**Comment by cgrayson** [comment]
That seems like a bug. Investigating.

**Comment by cgrayson** [comment]
This is indeed a bug. If you need to get this going immediately, you could use `{{lead.id}}` on the _left_ side: "Map {{lead.id}} to …"

**Comment by cgrayson** [comment]
This bug has been fixed and deployed to production. You should probably remove the existing mapping, save the flow, and then recreate it. Also note that you should refresh your browser to make sure it's running the new code before you do that.

**Comment by kcaponeAP** [comment]
To confirm, the correct mapping to have in place is:

Map: Reference Code to Lead ID

Correct?

**Comment by cgrayson** [comment]
No. [The last one](https://github.com/activeprospect/leadconduit-integration-velocify/issues/38#issuecomment-79222353), map Lead ID to lead.reference.

**Comment by kcaponeAP** [comment]
Verified to be fixed. TYVM!
