### ISSUE TITLE
First Name not being passed

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-velocify#43]
This lead:

https://next.leadconduit.com/events/55ad45d726b8a5c933c8f985?event_id=55ad45d826b8a5c933c8f98d&source_id=53d7ba989869170001000002&type=source

contains first_name in LCN, yet it was not passed onto Velocify. 
can someone tell me why this occurred?

**Comment by zalary** [comment]
I think this *was* submitted to Velocify.  If you look at the 'unformatted' version of the post, it contains the first name in the string.  I think this might we a weird bug in the formatted view, though I have no idea what would cause that.  cc @justinwinslow

**Comment by kcaponeAP** [comment]
Okay so a UI bug? Anyone need to reopen this in another repo?

**Comment by justinwinslow** [comment]
Looking

**Comment by justinwinslow** [comment]
If you click "View unformatted request body" it shows the first name. So, for some reason the syntax highlighting is not working properly.

**Comment by justinwinslow** [comment]
Client issue created here: https://github.com/activeprospect/leadconduit-client/issues/883
