### ISSUE TITLE
Change in location of XmlResponse=true in POST

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-velocify#45]
Recently, LC has been experiencing connection issues with Velocify.  In recent talks with their support team, they proclaimed that the location of XmlResponse=true is in the incorrect place.

Straight from Velocify:

"I noticed the XML=true is in the wrong area of the link. Use my link below for posting. Notice that its at the end of the URL

https://secure.velocify.com/Import.aspx?Provider=LeadConduitMortgage&Client=MortgageLendersOfAmerica&CampaignId=17&XmlResponse=true"

Upon further investigation, the URL example from inside the Velocify login area also states that it should be in a different location in the POST URL:

![screen shot 2015-07-24 at 12 54 32 pm](https://cloud.githubusercontent.com/assets/8238417/8881404/2f8c52e2-3205-11e5-8edb-c9bbb9d94ba7.png)

Can we make this change?

**Comment by alexkwolfe** [comment]
Yes. We can make this change, but I'll be very surprised if it has any effect. First, servers almost never rely on parameter ordering. Second, we always send the query string parameters in the same order. If this were a problem, it would be very unusual to have it cause problems sometimes but not others.

**Comment by alexkwolfe** [comment]
@ros3bud or @zalary, do you mind fixing this?

**Comment by zalary** [comment]
you bet.

**Comment by zalary** [comment]
resolves with Version 0.0.18

**Comment by kcaponeAP** [comment]
@alexkwolfe yes that was my fear that the parameter order would not matter. shrugs. thanks for putting someone on this. i can't track down the connection bug with their support team. hoping this makes it disappear.
