### ISSUE TITLE
Please remove prime_source & second_source

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-velocify#51]
These were supposed to be custom variables added to the Horizon Solar account, only -- as opposed to the entire Solar Integration.

@alexkwolfe @alexj

**Comment by alexj** [comment]
Lynda, could you please knock this out real quick?

Thanks,
Alex

**Comment by kcaponeAP** [comment]
This is for the solar integration. Sorry if that wasn't clear.

https://github.com/activeprospect/leadconduit-integration-velocify/blob/master/src/solar.coffee

**Comment by ros3bud** [comment]
Updated in 0.1.3
